//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace crud
{
    using System;
    using System.Collections.Generic;
    
    public partial class USERSYS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USERSYS()
        {
            this.USERSYS_LOGIN = new HashSet<USERSYS_LOGIN>();
        }
    
        public int ID { get; set; }
        public string USERNAME { get; set; }
        public string USERPASS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USERSYS_LOGIN> USERSYS_LOGIN { get; set; }
    }
}
